apiVersion: batch/v1
kind: CronJob
metadata:
  name: insertstockprice
  namespace: sandbox
spec:
  schedule: "30 8 * * 2-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: insertstockprice
              image: qroksera.com/sandbox/insertstockprice:202403050129
              imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: harbor
          restartPolicy: OnFailure
