apiVersion: batch/v1
kind: CronJob
metadata:
  name: insert_stock_price
  namespace: sandbox
spec:
  schedule: "30 8 * * 2-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: insert_stock_price
              image: qroksera.com/sandbox/insert_stock_price:202403041019
              imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: harbor
          restartPolicy: OnFailure
