apiVersion: batch/v1
kind: CronJob
metadata:
  name: insert-stock-price
  namespace: sandbox
spec:
  schedule: "30 8 * * 2-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: insert-stock-price
              image: qroksera.com/sandbox/insertStockPrice:202403041045
            - name: insert-stock-price
              image: qroksera.com/sandbox/insertStockPrice:202403041045
              imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: harbor
          restartPolicy: OnFailure
