apiVersion: batch/v1
kind: CronJob
metadata:
  name: insertstockprice
  namespace: sandbox
spec:
  schedule: "30 * * * 2-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: insertstockprice
              image: qroksera.com/sandbox/insertstockprice:202403060209
              imagePullPolicy: IfNotPresent
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack-secret
                      key: token
                - name: CHANNEL
                  valueFrom:
                    secretKeyRef:
                      name: slack-secret
                      key: channel
          imagePullSecrets:
            - name: harbor
          restartPolicy: OnFailure
