apiVersion: batch/v1
kind: CronJob
metadata:
  name: insertstockprice
  namespace: sandbox
spec:
  schedule: "*/4 * * * 2-6"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: insertstockprice
              image: qroksera.com/sandbox/insertstockprice:202403060526
              imagePullPolicy: IfNotPresent
              env:
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: slack-secret
                      key: token
                - name: CHANNEL
                  valueFrom:
                    secretKeyRef:
                      name: slack-secret
                      key: channel
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: postgre
                      key: uri
                - name: TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: SPREADSHEET_URL
                      key: url
                - name: CHANNEL
                  valueFrom:
                    secretKeyRef:
                      name: SPREADSHEET_PASSWORD
                      key: password
          imagePullSecrets:
            - name: harbor
          restartPolicy: OnFailure
